lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: 'allochat' # Make sure this matches your key's passphrase (if applicable)
    token_ttl: 3600 # Token lifetime (in seconds)